name: Enhancement Request
description: Enhancement Request
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request! Note that enhancement is an improvement on existing features, not a new feature.
  - type: textarea
    id: What enhancement would you like to see added to this project?
    attributes:
      label: What enhancement would you like to see added to this project?
      placeholder: Please describe your enhancement as detailed as possible. Note that enhancement is an improvement on existing features, not a new feature.
    validations:
      required: true
  - type: markdown
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md).