name: Feature Request
description: Feature Request
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: What feature would you like to see added to this project?
    attributes:
      label: What feature would you like to see added to this project?
      placeholder: Please describe your feature as detailed as possible.
    validations:
      required: true
  - type: markdown
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md).